import { Injectable } from '@nestjs/common';
import { QueryResult, QueryResultRow } from 'pg';
import { DatabaseService } from '../database/database.service';
import { slugifyNameForCompanyEmail } from '../auth/utils/credential-generator';

/** Same structural-typing trick as TemplatesService/OnboardingsService —
 *  lets recordCompanyEmail() run either standalone or as part of a
 *  caller's own transaction (see OnboardingsService.provisionCompanyEmail). */
interface Queryable {
  query<T extends QueryResultRow = QueryResultRow>(
    text: string,
    params?: unknown[],
  ): Promise<QueryResult<T>>;
}

export interface UserRow {
  id: string;
  full_name: string;
  phone_number: string;
  personal_email: string | null;
  joinee_id: string;
  company_email: string | null;
  company_email_active: boolean;
  must_reset_password: boolean;
  password_hash: string;
  login_otp_hash: string | null;
  login_otp_expires_at: Date | null;
  login_otp_attempts: number;
  role: 'superadmin_hr' | 'task_owner' | 'employee';
  department_id: string | null;
  status: 'invited' | 'active' | 'disabled';
  deleted_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

/** Fields safe to ever return from an API response. password_hash and
 *  the OTP bookkeeping columns are never included, period. */
export type PublicUser = Omit<
  UserRow,
  'password_hash' | 'login_otp_hash' | 'login_otp_expires_at' | 'login_otp_attempts'
>;

/** Digits only, no leading '+', no spaces/dashes. Applied on every write
 *  AND every read of phone_number so an exact-match lookup (mobile+OTP
 *  login) can't be defeated by formatting alone — e.g. '+91 98765
 *  43210', '9876543210', and '+919876543210' must all resolve to the
 *  same stored value. Migration 0018 normalizes rows written before
 *  this existed. */
function normalizePhoneNumber(raw: string): string {
  return raw.replace(/\D/g, '');
}

@Injectable()
export class UsersService {
  constructor(private readonly db: DatabaseService) {}

  /** joinee_id is intentionally not a parameter here — it's generated by
   *  the users.trg_users_set_joinee_id trigger (migration 0015), never
   *  by the application. */
  async insertUser(fields: {
    fullName: string;
    phoneNumber: string;
    personalEmail: string | null;
    passwordHash: string;
    role: string;
    departmentId: string | null;
  }): Promise<UserRow> {
    const { rows } = await this.db.query<UserRow>(
      `INSERT INTO users
         (full_name, phone_number, personal_email, password_hash, role,
          department_id, status, must_reset_password)
       VALUES ($1, $2, $3, $4, $5, $6, 'invited', true)
       RETURNING *`,
      [
        fields.fullName,
        normalizePhoneNumber(fields.phoneNumber),
        // Canonicalized on write for the same reason phone_number is:
        // uniqueness is already enforced case-insensitively by
        // users_personal_email_live_key, but storing the canonical form
        // means what's read back and matched on later is the same value
        // regardless of how HR typed it.
        fields.personalEmail?.trim().toLowerCase() ?? null,
        fields.passwordHash,
        fields.role,
        fields.departmentId,
      ],
    );
    return rows[0];
  }

  /** Existence only — deliberately not SELECT *, so a lookup that the
   *  login screen makes before anyone has authenticated never pulls a
   *  password hash or contact details into memory. */
  async existsByJoineeId(joineeId: string): Promise<boolean> {
    const { rowCount } = await this.db.query(
      `SELECT 1 FROM users WHERE joinee_id = $1 AND deleted_at IS NULL`,
      [joineeId],
    );
    return (rowCount ?? 0) > 0;
  }

  async findByJoineeId(joineeId: string): Promise<UserRow | null> {
    const { rows } = await this.db.query<UserRow>(
      `SELECT * FROM users WHERE joinee_id = $1 AND deleted_at IS NULL`,
      [joineeId],
    );
    return rows[0] ?? null;
  }

  // OTP-LOGIN-DISABLED — backed mobile-OTP login, which was its only
  // caller. Relied on the UNIQUE constraint on phone_number added
  // alongside joinee_id (migration 0015): without it, an OTP could
  // resolve to the wrong account if two users ever shared a number.
  // Normalized the input the same way insertUser normalizes storage, so
  // formatting differences never caused a false "Invalid credentials".
  //
  // async findByPhoneNumber(phoneNumber: string): Promise<UserRow | null> {
  //   const { rows } = await this.db.query<UserRow>(
  //     `SELECT * FROM users WHERE phone_number = $1 AND deleted_at IS NULL`,
  //     [normalizePhoneNumber(phoneNumber)],
  //   );
  //   return rows[0] ?? null;
  // }

  async findById(id: string): Promise<UserRow | null> {
    const { rows } = await this.db.query<UserRow>(
      `SELECT * FROM users WHERE id = $1 AND deleted_at IS NULL`,
      [id],
    );
    return rows[0] ?? null;
  }

  /** HR records the company email once IT/the company mail system has
   *  issued it. This is a record only — company_email is not, and has
   *  never been, a login identifier; the two real login methods are
   *  Joinee ID + password and mobile + OTP (AuthService), and this
   *  deliberately leaves password_hash/must_reset_password untouched
   *  so provisioning a company email can never strand someone out of
   *  their Joinee ID login. Accepts an optional queryable so
   *  OnboardingsService.provisionCompanyEmail (Step 17) can run this
   *  in the same transaction as its own onboardings.status flip. */
  async recordCompanyEmail(
    userId: string,
    companyEmail: string,
    queryable: Queryable = this.db,
  ) {
    await queryable.query(`UPDATE users SET company_email = $2 WHERE id = $1`, [
      userId,
      companyEmail,
    ]);
  }

  /** Deterministic collision handling for a REAL company email:
   *  "Sam Row" -> samrow@domain, and if that's taken (another Sam Row)
   *  -> samrow1@domain, samrow2@domain, ... — unlike the synthetic
   *  temp login's random suffix, this has to read as a normal address
   *  and stay stable, so it's an incrementing integer, not randomness.
   *  Checked against the SAME queryable the caller inserts under, so
   *  this can run inside OnboardingsService.provisionCompanyEmail's
   *  transaction without racing a concurrent read outside it. */
  async generateUniqueCompanyEmail(
    fullName: string,
    domain: string,
    queryable: Queryable = this.db,
  ): Promise<string> {
    const base = slugifyNameForCompanyEmail(fullName);
    let suffix = 0;
    while (true) {
      const candidate = suffix === 0 ? `${base}@${domain}` : `${base}${suffix}@${domain}`;
      const { rows } = await queryable.query<{ id: string }>(
        `SELECT id FROM users WHERE company_email = $1`,
        [candidate],
      );
      if (rows.length === 0) return candidate;
      suffix++;
    }
  }

  /** Overwrites the password hash. forceReset=true (the default for any
   *  admin-issued temp password) also flips must_reset_password so the
   *  temp value can never quietly become a permanent one. */
  async setPasswordHash(
    userId: string,
    passwordHash: string,
    forceReset = true,
  ) {
    await this.db.query(
      `UPDATE users SET password_hash = $2, must_reset_password = $3 WHERE id = $1`,
      [userId, passwordHash, forceReset],
    );
  }

  async activateUser(userId: string) {
    await this.db.query(`UPDATE users SET status = 'active' WHERE id = $1`, [
      userId,
    ]);
  }

  // OTP-LOGIN-DISABLED — the three login-OTP writers. The login_otp_*
  // COLUMNS are deliberately left in the schema and in UserRow: they
  // still hold whatever was there when OTP login was switched off, and
  // toPublicUser below must keep stripping them regardless.
  //
  // /** Stores a freshly generated login OTP (already hashed — the plain
  //  *  code never touches the database) and resets the attempt counter,
  //  *  whether this is the first code this session or a resend. */
  // async setLoginOtp(userId: string, otpHash: string, expiresAt: Date) {
  //   await this.db.query(
  //     `UPDATE users
  //      SET login_otp_hash = $2, login_otp_expires_at = $3, login_otp_attempts = 0
  //      WHERE id = $1`,
  //     [userId, otpHash, expiresAt],
  //   );
  // }
  //
  // /** Called on successful verification, expiry, or lockout — a spent or
  //  *  dead code must never verify again. */
  // async clearLoginOtp(userId: string) {
  //   await this.db.query(
  //     `UPDATE users
  //      SET login_otp_hash = NULL, login_otp_expires_at = NULL, login_otp_attempts = 0
  //      WHERE id = $1`,
  //     [userId],
  //   );
  // }
  //
  // async incrementOtpAttempts(userId: string): Promise<number> {
  //   const { rows } = await this.db.query<{ login_otp_attempts: number }>(
  //     `UPDATE users SET login_otp_attempts = login_otp_attempts + 1
  //      WHERE id = $1
  //      RETURNING login_otp_attempts`,
  //     [userId],
  //   );
  //   return rows[0].login_otp_attempts;
  // }

  /** Strips fields that must never leave the API. */
  toPublicUser(user: UserRow): PublicUser {
    const { password_hash, login_otp_hash, login_otp_expires_at, login_otp_attempts, ...rest } =
      user;
    return rest;
  }
}
