import {
  ForbiddenException,
  Injectable,
  NotFoundException,
  UnauthorizedException,
} from '@nestjs/common';
import * as bcrypt from 'bcrypt';
import { UsersService, UserRow } from '../users/users.service';
import { ActivityLogService } from '../activity-log/activity-log.service';
import { CreateUserDto } from './dto/create-user.dto';
import { generateTempPassword } from './utils/credential-generator';
import {
  generateOtpCode,
  hashOtp,
  verifyOtpHash,
  sendOtpSms,
  OTP_TTL_MS,
  OTP_MAX_ATTEMPTS,
} from './utils/otp';
import { TokenService } from './tokens/token.service';

const BCRYPT_ROUNDS = 12;

type AuthenticatedResult = {
  status: 'authenticated';
  accessToken: string;
  refreshToken: string;
  user: ReturnType<UsersService['toPublicUser']>;
};

/** Method 1 (Joinee ID + password) can end in one of two shapes: fully
 *  authenticated, or "here's a password-reset pre-auth token" if the
 *  password on file is still the HR-issued temp one. Method 2 (mobile
 *  OTP) never has a reset step, so its own results are always
 *  AuthenticatedResult once verified. */
type PasswordLoginResult =
  | AuthenticatedResult
  | { status: 'password_reset_required'; preAuthToken: string };

@Injectable()
export class AuthService {
  constructor(
    private readonly usersService: UsersService,
    private readonly tokens: TokenService,
    private readonly activityLog: ActivityLogService,
  ) {}

  async createUser(dto: CreateUserDto, actorId: string) {
    const tempPassword = generateTempPassword();
    const passwordHash = await bcrypt.hash(tempPassword, BCRYPT_ROUNDS);

    // joinee_id is generated by the DB trigger (migration 0015), not
    // here — no collision-retry loop needed, unlike the old random
    // synthetic temp email.
    const user = await this.usersService.insertUser({
      fullName: dto.fullName,
      phoneNumber: dto.phoneNumber,
      personalEmail: dto.personalEmail ?? null,
      passwordHash,
      role: dto.role,
      departmentId: dto.departmentId ?? null,
    });

    // Role/department are fine to log — never the temp password or
    // its hash, which never leave this method except in the one-time
    // credentials payload below.
    await this.activityLog.log({
      actorId,
      action: 'user.created',
      entityType: 'user',
      entityId: user.id,
      metadata: { role: dto.role, departmentId: dto.departmentId ?? null },
    });

    return {
      user: this.usersService.toPublicUser(user),
      credentials: {
        joineeId: user.joinee_id,
        temporaryPassword: tempPassword,
        note: 'Shown once. Deliver to the employee directly — this will not be shown again.',
      },
    };
  }

  /**
   * What HR sees when they reopen the credentials popup after closing it.
   *
   * The Joinee ID comes back; the temporary password cannot. It is
   * bcrypt-hashed into password_hash the moment it's generated, and
   * bcrypt is one-way — the only way to show the same string twice would
   * be to also store it readably, which would make this the single
   * plaintext credential in the schema. `canRegenerate` is what replaces
   * that: if HR lost the password before passing it on, they issue a new
   * one, which is operationally identical because the old one was never
   * used yet.
   *
   * `hasLoggedIn` tells HR whether the credentials are still needed at
   * all — an active account past its forced reset has its own password
   * and regenerating would lock the user out of it.
   */
  async getCredentialsSummary(userId: string, actorId: string) {
    const user = await this.usersService.findById(userId);
    if (!user) throw new NotFoundException('User not found');

    await this.activityLog.log({
      actorId,
      action: 'user.credentials_viewed',
      entityType: 'user',
      entityId: userId,
    });

    return {
      joineeId: user.joinee_id,
      fullName: user.full_name,
      phoneNumber: user.phone_number,
      personalEmail: user.personal_email,
      awaitingFirstReset: user.must_reset_password,
      hasLoggedIn: user.status !== 'invited',
      temporaryPassword: null,
      note: 'The temporary password is stored only as a one-way hash and cannot be shown again. Regenerate to issue a new one.',
      canRegenerate: true,
    };
  }

  async regenerateCredentials(userId: string, actorId: string) {
    const user = await this.usersService.findById(userId);
    if (!user) throw new NotFoundException('User not found');

    const tempPassword = generateTempPassword();
    const passwordHash = await bcrypt.hash(tempPassword, BCRYPT_ROUNDS);
    await this.usersService.setPasswordHash(userId, passwordHash); // forceReset defaults true

    await this.activityLog.log({
      actorId,
      action: 'user.credentials_regenerated',
      entityType: 'user',
      entityId: userId,
    });

    return {
      credentials: {
        loginId: user.joinee_id,
        temporaryPassword: tempPassword,
        note: 'Shown once. Deliver to the employee directly — this will not be shown again.',
      },
    };
  }

  /** Shared by every path that ends in a real session: activates a
   *  still-'invited' account on its very first successful login (by
   *  either method) and signs the real token pair. */
  private async issueTokens(user: UserRow): Promise<AuthenticatedResult> {
    if (user.status === 'invited') {
      await this.usersService.activateUser(user.id);
      user.status = 'active'; // keep the response consistent with what we just wrote
    }
    return {
      status: 'authenticated',
      accessToken: this.tokens.signAccessToken(user),
      refreshToken: this.tokens.signRefreshToken(user),
      user: this.usersService.toPublicUser(user),
    };
  }

  private async issueLoginOtp(user: UserRow): Promise<void> {
  const code = generateOtpCode();

  console.log('========================');
  console.log('OTP GENERATED:', code);
  console.log('PHONE:', user.phone_number);
  console.log('========================');

  const otpHash = await hashOtp(code);
  const expiresAt = new Date(Date.now() + OTP_TTL_MS);

  await this.usersService.setLoginOtp(
    user.id,
    otpHash,
    expiresAt,
  );

  console.log('OTP SAVED TO DATABASE');

  await sendOtpSms(user.phone_number, code);

  console.log('SMS FUNCTION FINISHED');
}

  // ============================================================
  // Method 1 — Joinee ID + password. No company email, no OTP.
  // ============================================================

  async loginWithPassword(joineeId: string, password: string): Promise<PasswordLoginResult> {
    const user = await this.usersService.findByJoineeId(joineeId);
    if (!user) throw new UnauthorizedException('Invalid credentials');
    if (user.status === 'disabled') {
      throw new ForbiddenException('This account has been disabled');
    }

    const passwordOk = await bcrypt.compare(password, user.password_hash);
    if (!passwordOk) throw new UnauthorizedException('Invalid credentials');

    if (user.must_reset_password) {
      return {
        status: 'password_reset_required',
        preAuthToken: this.tokens.signPreAuth(user.id, 'password_reset'),
      };
    }
    return this.issueTokens(user);
  }

  /**
   * Sets the real password and deliberately does NOT issue a session:
   * the user is sent back to the login page to sign in with their Joinee
   * ID and the password they just chose. That extra round trip is the
   * point — it proves the new password actually works before the user
   * relies on it, and it means a pre-auth token can never be traded
   * straight for a full session.
   */
  async completePasswordReset(
    userId: string,
    newPassword: string,
  ): Promise<{ status: 'password_reset_complete'; joineeId: string }> {
    const user = await this.usersService.findById(userId);
    if (!user) throw new NotFoundException('User not found');

    const passwordHash = await bcrypt.hash(newPassword, BCRYPT_ROUNDS);
    await this.usersService.setPasswordHash(userId, passwordHash, false);

    await this.activityLog.log({
      actorId: userId,
      action: 'user.password_reset_completed',
      entityType: 'user',
      entityId: userId,
    });

    // Returned so the login screen can prefill the identifier the user
    // is about to type back in.
    return { status: 'password_reset_complete', joineeId: user.joinee_id };
  }

  // ============================================================
  // Method 2 — mobile number + OTP. No password involved at all.
  // ============================================================

  async requestMobileOtp(phoneNumber: string): Promise<{ preAuthToken: string }> {
    const user = await this.usersService.findByPhoneNumber(phoneNumber);
    // Same generic message either way — doesn't confirm/deny whether a
    // number is registered.
    if (!user) throw new UnauthorizedException('Invalid credentials');
    if (user.status === 'disabled') {
      throw new ForbiddenException('This account has been disabled');
    }

    await this.issueLoginOtp(user);
    return { preAuthToken: this.tokens.signPreAuth(user.id, 'otp_login') };
  }

  async verifyMobileOtp(userId: string, code: string): Promise<PasswordLoginResult> {
    const user = await this.usersService.findById(userId);
    if (!user) throw new NotFoundException('User not found');

    if (!user.login_otp_hash || !user.login_otp_expires_at) {
      throw new UnauthorizedException('No verification code pending — request a new one');
    }
    if (user.login_otp_expires_at.getTime() < Date.now()) {
      await this.usersService.clearLoginOtp(userId);
      throw new UnauthorizedException('Verification code expired — request a new one');
    }
    if (user.login_otp_attempts >= OTP_MAX_ATTEMPTS) {
      await this.usersService.clearLoginOtp(userId);
      throw new UnauthorizedException('Too many attempts — request a new code');
    }

    const codeOk = await verifyOtpHash(code, user.login_otp_hash);
    if (!codeOk) {
      await this.usersService.incrementOtpAttempts(userId);
      throw new UnauthorizedException('Invalid code');
    }

    await this.usersService.clearLoginOtp(userId);

    // A first-time login must set a real password before it gets a
    // session, whichever method got the user here. Proving identity by
    // OTP is what authorizes the reset — the user has never seen the
    // HR-issued temp password and doesn't need to. The token is minted
    // with the 'password_reset' purpose, so the OTP pre-auth token this
    // call consumed can't be replayed against the reset endpoint.
    if (user.must_reset_password) {
      return {
        status: 'password_reset_required',
        preAuthToken: this.tokens.signPreAuth(user.id, 'password_reset'),
      };
    }

    return this.issueTokens(user);
  }

  async resendMobileOtp(userId: string): Promise<{ sent: true }> {
    const user = await this.usersService.findById(userId);
    if (!user) throw new NotFoundException('User not found');
    await this.issueLoginOtp(user);
    return { sent: true };
  }

  // ============================================================
  // Token refresh
  // ============================================================

  async refreshAccessToken(userId: string) {
    const user = await this.usersService.findById(userId);
    if (!user || user.status !== 'active') {
      throw new UnauthorizedException('Invalid refresh token');
    }
    return {
      accessToken: this.tokens.signAccessToken(user),
      // Rotated on every refresh. Note: this is stateless rotation —
      // there's no server-side record of issued/revoked refresh tokens
      // yet, so an old refresh token technically still verifies until
      // it expires on its own. A refresh_tokens table with a revoked
      // flag would close that gap; flagging it rather than pretending
      // rotation alone is full revocation.
      refreshToken: this.tokens.signRefreshToken(user),
    };
  }
}
